
#spring:
#  application:
#    name: zf-erueka-server
#server:
#  port: 8761

#eureka集群配置如下：
---
spring:
  application:
    name: eureka-server-clustered
  profiles: primary

server:
  port: 8761 
eureka:
  instance:
    hostname: eureka-primary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-secondary:8762/eureka/,http://eureka-tertiary:8763/eureka/
      
---

spring:
  application:
    name: eureka-server-clustered
  profiles: secondary

server:
  port: 8762 
eureka:
  instance:
    hostname: eureka-secondary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-tertiary:8763/eureka/,http://eureka-primary:8761/eureka/    
---

spring:
  application:
    name: eureka-server-clustered
  profiles: tertiary

server:
  port: 8763 
eureka:
  instance:
    hostname: eureka-tertiary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-primary:8761/eureka/,http://eureka-secondary:8762/eureka/    
