#第一种方式：在application.yml中指定erureka(注册中心)的地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

# 第二种方式，通过git获取erureka(注册中心)的地址,这时需要在git的repository里添加application.yml，如下（应该把#号去掉）：
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#words: 喜欢1,喜欢2,喜欢3,喜欢4,喜欢5

server:
  port: 8803

spring:
  application:
    name: zf-erueka-client3